# Generated by Django 4.1.7 on 2023-03-28 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0003_auto_20230216_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kickofftime',
            options={'ordering': ['gameweek'], 'verbose_name': 'PL - Kickoff Time', 'verbose_name_plural': 'PL - Kickoff Times'},
        ),
        migrations.AlterModelOptions(
            name='premierleagueteaminfo',
            options={'ordering': ['team_id', '-team_name', 'team_short_name'], 'verbose_name': 'PL - Fixturedata', 'verbose_name_plural': 'PL - Fixturedata'},
        ),
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 28), help_text='Date entered into database'),
        ),
    ]
