# Generated by Django 3.1.4 on 2024-08-08 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0010_auto_20240716_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2024, 8, 8), help_text='Date entered into database'),
        ),
    ]
