# Generated by Django 3.1.4 on 2021-08-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fplplayersmodel',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id']},
        ),
    ]
