# Generated by Django 3.1.4 on 2021-10-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0006_auto_20211010_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configvalues',
            old_name='date_updated',
            new_name='date_last_updated',
        ),
    ]
