# Generated by Django 3.1.4 on 2021-10-10 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0007_auto_20211010_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configvalues',
            name='date_last_updated',
            field=models.DateField(default=datetime.date(2021, 10, 10)),
        ),
    ]
