# Generated by Django 3.1.4 on 2021-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0016_auto_20211010_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwschecked',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='gwschecked',
            name='player_id',
        ),
        migrations.AlterField(
            model_name='gwschecked',
            name='id',
            field=models.IntegerField(default=1, help_text='Enter team id (1) ', primary_key=True, serialize=False),
        ),
    ]
