# Generated by Django 3.1.4 on 2021-10-17 14:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0017_auto_20211010_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfoStatistics',
            fields=[
                ('gw', models.IntegerField(help_text='Enter gameweek number (1) ', primary_key=True, serialize=False)),
                ('extra_info_top_1', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1'), size=8)),
                ('extra_info_top_10', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10'), size=8)),
                ('extra_info_top_100', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 100'), size=8)),
                ('extra_info_top_1000', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1000'), size=8)),
                ('extra_info_top_10000', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10000'), size=8)),
            ],
            options={
                'ordering': ['gw'],
            },
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_31',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 31'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_32',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 32'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_33',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 33'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_34',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 34'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_35',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 35'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_36',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 36'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_37',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 37'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_38',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 38'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats100',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_31',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 31'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_32',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 32'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_33',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 33'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_34',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 34'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_35',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 35'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_36',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 36'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_37',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 37'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_38',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 38'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats1000',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_31',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 31'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_32',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 32'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_33',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 33'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_34',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 34'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_35',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 35'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_36',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 36'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_37',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 37'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_38',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 38'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), size=6),
        ),
        migrations.AlterField(
            model_name='globalownershipstats10000',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), size=6),
        ),
    ]
