# Generated by Django 3.1.4 on 2021-10-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0020_fplplayersmodel_player_web_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fplplayersmodel',
            name='player_name',
            field=models.CharField(help_text='Enter player name (Bruno Miguel & Borges Fernandes) ', max_length=40),
        ),
        migrations.AlterField(
            model_name='fplplayersmodel',
            name='player_web_name',
            field=models.CharField(help_text='Enter player web name (Fernandes) ', max_length=40),
        ),
    ]
