# Generated by Django 3.1.4 on 2022-07-25 16:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0028_userinfostatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1'), default=[0, 0, 0, 0, 0, 0], size=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10'), default=[0, 0, 0, 0, 0, 0], size=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_100',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 100'), default=[0, 0, 0, 0, 0, 0], size=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_1000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1000'), default=[0, 0, 0, 0, 0, 0], size=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_5000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10000'), default=[0, 0, 0, 0, 0, 0], size=6),
            preserve_default=False,
        ),
    ]
