# Generated by Django 3.1.4 on 2022-07-29 15:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0030_auto_20220726_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteserienPlayerStatistic',
            fields=[
                ('player_id', models.IntegerField(help_text='Enter team id (1) ', primary_key=True, serialize=False)),
                ('player_team_id', models.IntegerField(help_text='Enter team id for this player (1)  ')),
                ('player_position_id', models.IntegerField(help_text='Enter position id for this player (2) ')),
                ('player_name', models.CharField(help_text='Enter player name (Bruno Miguel & Borges Fernandes) ', max_length=40)),
                ('player_web_name', models.CharField(help_text='Enter player web name (Fernandes) ', max_length=40)),
                ('chance_of_playing', models.CharField(help_text='Enter chance of playing next round (75%) ', max_length=5)),
                ('assists_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of assist (2)'), size=31)),
                ('bonus_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of bonus (3)'), size=31)),
                ('bps_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of bps (21)'), size=31)),
                ('clean_sheets_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Clean sheets (1/0)'), size=31)),
                ('creativity_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter number of creativity (10.2)', max_length=4), size=31)),
                ('goals_conceded_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of goals_conceded (2)'), size=31)),
                ('goals_scored_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of goals_scored in this match by this team (2)'), size=31)),
                ('ict_index_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter number of ict_index (3.6)', max_length=4), size=31)),
                ('influence_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter number of influence (10.6)', max_length=4), size=31)),
                ('minutes_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of minutes played (61)'), size=31)),
                ('opponent_team_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter opponent_team index (6)'), size=31)),
                ('own_goals_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of own_goals (2)'), size=31)),
                ('penalties_missed_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of penalties_missed (1)'), size=31)),
                ('penalties_saved_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of penalties_saved (0)'), size=31)),
                ('red_cards_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of red_cards (0)'), size=31)),
                ('round_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter gw/round number (28)'), size=31)),
                ('saves_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of saves (6)'), size=31)),
                ('selected_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter number of people selected this player (335552)'), size=31)),
                ('team_a_score_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter goals scored by away team (3)', max_length=5), size=31)),
                ('team_h_score_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter goals scored by home team (1)', max_length=5), size=31)),
                ('threat_list', django_mysql.models.ListTextField(models.CharField(help_text='Enter threat value (10.0)', max_length=4), size=31)),
                ('total_points_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter total_points (12)'), size=31)),
                ('transfers_balance_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter transfers_balance (-140303)'), size=31)),
                ('transfers_in_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter transfers_in (71659)'), size=31)),
                ('transfers_out_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter transfers_out (216199)'), size=31)),
                ('value_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Enter value (126)'), size=31)),
                ('was_home_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Played a home game? (1/0)'), size=31)),
                ('yellow_cards_list', django_mysql.models.ListTextField(models.IntegerField(help_text='Number of yellow_cards (1)'), size=31)),
            ],
            options={
                'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'],
            },
        ),
    ]
