# Generated by Django 3.1.4 on 2022-07-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0031_eliteserienplayerstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eliteserienplayerstatistic',
            name='bps_list',
        ),
        migrations.RemoveField(
            model_name='eliteserienplayerstatistic',
            name='creativity_list',
        ),
        migrations.RemoveField(
            model_name='eliteserienplayerstatistic',
            name='ict_index_list',
        ),
        migrations.RemoveField(
            model_name='eliteserienplayerstatistic',
            name='influence_list',
        ),
        migrations.RemoveField(
            model_name='eliteserienplayerstatistic',
            name='threat_list',
        ),
    ]
