# Generated by Django 3.1.4 on 2022-08-03 14:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0032_auto_20220729_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfostatistics',
            name='ranking_history',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Year,points,ranking -- 2019,1961,1586', max_length=20), blank=True, size=5),
        ),
    ]
