# Generated by Django 3.1.4 on 2022-08-07 08:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0033_userinfostatistics_ranking_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipsAndUserInfo',
            fields=[
                ('gw', models.IntegerField(help_text='Enter gameweek number (1) ', primary_key=True, serialize=False)),
                ('extra_info_top_1', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1'), size=10)),
                ('extra_info_top_10', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10'), size=10)),
                ('extra_info_top_100', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 100'), size=10)),
                ('extra_info_top_1000', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1000'), size=10)),
                ('extra_info_top_10000', django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10000'), size=10)),
                ('total_chip_usage_1', django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1'), blank=True, size=6)),
                ('total_chip_usage_10', django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10'), blank=True, size=6)),
                ('total_chip_usage_100', django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 100'), blank=True, size=6)),
                ('total_chip_usage_1000', django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1000'), blank=True, size=6)),
                ('total_chip_usage_5000', django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10000'), blank=True, size=6)),
            ],
            options={
                'ordering': ['gw'],
            },
        ),
        migrations.DeleteModel(
            name='ExtraInfoStatistics',
        ),
    ]
