# Generated by Django 3.1.4 on 2022-10-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0040_eliteseriencupstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteseriencupstatistics',
            old_name='ranking_history',
            new_name='cup_history',
        ),
    ]
