# Generated by Django 4.1.7 on 2023-03-28 16:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0041_auto_20221009_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eliteserienchipsanduserinfo',
            options={'ordering': ['gw'], 'verbose_name': 'ESF - Chip and User stat', 'verbose_name_plural': 'ESF - Chip and User stats'},
        ),
        migrations.AlterModelOptions(
            name='eliteseriencupstatistics',
            options={'ordering': ['name', 'team_name'], 'verbose_name': 'ESF - Cup stat', 'verbose_name_plural': 'ESF - Cup stats'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienglobalownershipstats100',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'ESF - Ownership stat (100)', 'verbose_name_plural': 'ESF - Ownership stats (100)'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienglobalownershipstats1000',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'ESF - Ownership stat (1000)', 'verbose_name_plural': 'ESF - Ownership stats (1000)'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienglobalownershipstats5000',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'ESF - Ownership stat (5000)', 'verbose_name_plural': 'ESF - Ownership stats (5000)'},
        ),
        migrations.AlterModelOptions(
            name='eliteseriengwschecked',
            options={'ordering': ['id'], 'verbose_name': 'ESF - Updated GW', 'verbose_name_plural': 'ESF - Updated GWs'},
        ),
        migrations.AlterModelOptions(
            name='eliteseriennationalitystatistics',
            options={'ordering': ['country_name', 'number_of_managers_from_this_country', 'country_code'], 'verbose_name': 'ESF - Nationality stat', 'verbose_name_plural': 'ESF - Nationality stats'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienplayerstatistic',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'ESF - Player stat', 'verbose_name_plural': 'ESF - Player stats'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienrankandpoints',
            options={'ordering': ['gw'], 'verbose_name': 'ESF - Ranking stat', 'verbose_name_plural': 'ESF - Ranking stats'},
        ),
        migrations.AlterModelOptions(
            name='eliteserienuserinfostatistics',
            options={'ordering': ['user_id', 'user_first_name', 'user_last_name', 'user_team_name'], 'verbose_name': 'ESF - User stat', 'verbose_name_plural': 'ESF - User stats'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguechipsanduserinfo',
            options={'ordering': ['gw'], 'verbose_name': 'PL - Chip and User stat', 'verbose_name_plural': 'PL - Chip and User stats'},
        ),
        migrations.AlterModelOptions(
            name='premierleagueglobalownershipstats100',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'PL - Ownership stat (100)', 'verbose_name_plural': 'PL - Ownership stats (100)'},
        ),
        migrations.AlterModelOptions(
            name='premierleagueglobalownershipstats1000',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'PL - Ownership stat (1000)', 'verbose_name_plural': 'PL - Ownership stats (1000)'},
        ),
        migrations.AlterModelOptions(
            name='premierleagueglobalownershipstats10000',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'PL - Ownership stat (10000)', 'verbose_name_plural': 'PL - Ownership stats (10000)'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguegwschecked',
            options={'ordering': ['id'], 'verbose_name': 'PL - Updated GW', 'verbose_name_plural': 'PL - Updated GWs'},
        ),
        migrations.AlterModelOptions(
            name='premierleaguenationalitystatistics',
            options={'ordering': ['country_name', 'number_of_managers_from_this_country', 'country_code'], 'verbose_name': 'PL - Nationality stat', 'verbose_name_plural': 'PL - Nationality stats'},
        ),
        migrations.AlterModelOptions(
            name='premierleagueplayers',
            options={'ordering': ['player_id', 'player_name', 'player_team_id', 'player_position_id'], 'verbose_name': 'PL - Player stat', 'verbose_name_plural': 'PL - Player stats'},
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_assists_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_assists (0.06)', max_length=4), blank=True, null=True, size=39),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_assists_per_90',
            field=models.CharField(blank=True, help_text='Enter expected assists per 90 min (0.72) ', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goal_involvements_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goal_involvements (0.20)', max_length=4), blank=True, null=True, size=39),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goal_involvements_per_90',
            field=models.CharField(blank=True, help_text='Enter expected goal involvements per 90 min (0.31) ', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goals_conceded_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goals_conceded (1.6)', max_length=4), blank=True, null=True, size=39),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goals_conceded_per_90',
            field=models.CharField(blank=True, help_text='Enter expected goals conceded per 90 min (1.11) ', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goals_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goals (0.36)', max_length=4), blank=True, null=True, size=39),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='expected_goals_per_90',
            field=models.CharField(blank=True, help_text='Enter expected goals per 90 min (0.11) ', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='goals_conceded_per_90',
            field=models.CharField(blank=True, help_text='Enter goals conceded per 90 min (0.41) ', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='saves_per_90',
            field=models.CharField(blank=True, help_text='Enter saves per 90 min (0) ', max_length=6, null=True),
        ),
    ]
