# Generated by Django 4.1.7 on 2023-04-20 17:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0043_eliteserienplayerstatistic_opta_index_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteserienplayerstatistic',
            name='fixture_id_list',
            field=django_mysql.models.ListTextField(models.IntegerField(blank=True, help_text='Fixture id (9)', null=True), default='', size=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eliteserienplayerstatistic',
            name='opta_index_list',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, help_text='Opta index ("47.810070")', max_length=10, null=True), size=31),
        ),
    ]
