# Generated by Django 4.1.7 on 2023-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0047_eliteserienchipsanduserinfo_number_of_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteserienplayerstatistic',
            name='player_status',
            field=models.CharField(blank=True, help_text='Player status (a=available, u=unavailble,i,d)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='player_status',
            field=models.CharField(blank=True, help_text='Player status (a=available, u=unavailble,i,d)', max_length=1, null=True),
        ),
    ]
