# Generated by Django 3.1.4 on 2024-07-16 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0050_auto_20240527_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteserienplayerstatistic',
            name='player_created_date',
            field=models.DateField(default=datetime.date(2024, 7, 16), help_text='Date entered into database'),
        ),
        migrations.AddField(
            model_name='premierleagueplayers',
            name='player_created_date',
            field=models.DateField(default=datetime.date(2024, 7, 16), help_text='Date entered into database'),
        ),
    ]
