# Generated by Django 3.1.4 on 2023-02-09 17:13

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KickOffTime',
            fields=[
                ('gameweek', models.IntegerField(help_text='Gameweek number', primary_key=True, serialize=False)),
                ('kickoff_time', models.CharField(help_text='Kickoff time for given gameweek', max_length=20)),
                ('day_month', models.CharField(help_text='Kickoff time short version (12. jan)', max_length=7)),
            ],
            options={
                'ordering': ['gameweek'],
            },
        ),
        migrations.CreateModel(
            name='PremierLeagueTeamInfo',
            fields=[
                ('team_name', models.CharField(help_text='Enter team name (Arsenal)', max_length=30)),
                ('team_id', models.IntegerField(help_text='Enter team id (1) ', primary_key=True, serialize=False)),
                ('team_short_name', models.CharField(help_text='Enter team name short (ARS)', max_length=3)),
                ('date', models.DateField(default=datetime.date(2023, 2, 9), help_text='Date entered into database')),
                ('oppTeamNameList', django_mysql.models.ListTextField(models.CharField(help_text='Enter team name short (ARS)', max_length=3), size=38)),
                ('oppTeamHomeAwayList', django_mysql.models.ListTextField(models.CharField(help_text='H/A', max_length=1), size=38)),
                ('oppTeamDifficultyScore', django_mysql.models.ListTextField(models.IntegerField(help_text='1-5'), size=38)),
                ('gw', django_mysql.models.ListTextField(models.IntegerField(help_text='1-38'), size=38)),
            ],
            options={
                'ordering': ['team_id', '-team_name', 'team_short_name'],
            },
        ),
    ]
