# Generated by Django 3.1.4 on 2023-02-16 16:32

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premierleagueteaminfo',
            name='possibleBlank',
            field=django_mysql.models.ListTextField(models.CharField(help_text='?', max_length=1), default='?', size=38),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 16), help_text='Date entered into database'),
        ),
    ]
