# Generated by Django 4.1.7 on 2023-04-20 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0005_alter_premierleagueteaminfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 20), help_text='Date entered into database'),
        ),
    ]
