# Generated by Django 4.1.7 on 2023-05-09 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0006_alter_premierleagueteaminfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 9), help_text='Date entered into database'),
        ),
    ]
