# Generated by Django 3.1.4 on 2024-05-27 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0008_alter_premierleagueteaminfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleagueteaminfo',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 27), help_text='Date entered into database'),
        ),
    ]
