# Generated by Django 3.1.4 on 2021-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0005_auto_20211010_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configvalues',
            options={'ordering': ['gws_updated']},
        ),
        migrations.AddField(
            model_name='configvalues',
            name='date_updated',
            field=models.DateField(default="2021-01-01"),
            preserve_default=False,
        ),
    ]
