# Generated by Django 3.1.4 on 2021-10-10 14:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0010_remove_configvalues_date_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GwsChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gws_updated', django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), size=38)),
            ],
            options={
                'ordering': ['gws_updated'],
            },
        ),
        migrations.DeleteModel(
            name='ConfigValues',
        ),
    ]
