# Generated by Django 3.1.4 on 2021-10-10 14:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0011_auto_20211010_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwschecked',
            options={'ordering': ['date_modified']},
        ),
        migrations.RemoveField(
            model_name='gwschecked',
            name='gws_updated',
        ),
        migrations.AddField(
            model_name='gwschecked',
            name='date_modified',
            field=models.CharField(default='2021', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwschecked',
            name='gws_updated_100',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), default='2021', size=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwschecked',
            name='gws_updated_1000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), default='2021', size=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwschecked',
            name='gws_updated_10000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), default='2021', size=38),
            preserve_default=False,
        ),
    ]
