# Generated by Django 3.1.4 on 2021-10-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0015_auto_20211010_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwschecked',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gwschecked',
            name='player_id',
            field=models.IntegerField(default=1, help_text='Enter team id (1) '),
        ),
    ]
