# Generated by Django 3.1.4 on 2022-07-15 13:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0022_eliteserienchipsanduserinfo_eliteserienglobalownershipstats100_eliteserienglobalownershipstats1000_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteserienGwsChecked',
            fields=[
                ('id', models.IntegerField(default=1, help_text='Enter team id (1) ', primary_key=True, serialize=False)),
                ('date_modified', models.CharField(max_length=20)),
                ('gws_updated_100', django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), size=38)),
                ('gws_updated_1000', django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), size=38)),
                ('gws_updated_10000', django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), size=38)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
