# Generated by Django 3.1.4 on 2022-07-18 16:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0026_auto_20220718_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteserienglobalownershipstats100',
            name='gws_updated',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), blank=True, size=38),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats100',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats1000',
            name='gws_updated',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='All GWs that have been updated'), blank=True, size=38),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 1'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 10'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_11',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 11'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_12',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 12'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_13',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 13'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_14',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 14'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_15',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 15'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_16',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 16'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_17',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 17'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_18',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 18'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_19',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 19'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_2',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 2'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_20',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 20'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_21',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 21'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_22',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 22'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_23',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 23'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_24',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 24'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_25',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 25'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_26',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 26'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_27',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 27'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_28',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 28'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_29',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 29'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_3',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 3'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_30',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 30'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_4',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 4'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_5',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 5'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_6',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 6'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_7',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 7'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_8',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 8'), blank=True, size=7),
        ),
        migrations.AlterField(
            model_name='eliteserienglobalownershipstats5000',
            name='gw_9',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Ownership GW 9'), blank=True, size=7),
        ),
    ]
