# Generated by Django 3.1.4 on 2022-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0027_auto_20220718_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoStatistics',
            fields=[
                ('user_id', models.IntegerField(help_text='Enter user id (1)', primary_key=True, serialize=False)),
                ('user_team_name', models.CharField(help_text='Enter team name', max_length=40)),
                ('user_first_name', models.CharField(help_text='Enter user first name', max_length=40)),
                ('user_last_name', models.CharField(help_text='Enter user last name', max_length=40)),
            ],
            options={
                'ordering': ['user_id', 'user_first_name', 'user_last_name', 'user_team_name'],
            },
        ),
    ]
