# Generated by Django 3.1.4 on 2022-07-26 19:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0029_auto_20220725_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='extra_info_top_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1'), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='extra_info_top_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10'), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='extra_info_top_100',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 100'), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='extra_info_top_1000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 1000'), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='extra_info_top_5000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Extra info among top 10000'), blank=True, size=10),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_1',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1'), blank=True, size=6),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_10',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10'), blank=True, size=6),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_100',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 100'), blank=True, size=6),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_1000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 1000'), blank=True, size=6),
        ),
        migrations.AlterField(
            model_name='eliteserienchipsanduserinfo',
            name='total_chip_usage_5000',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='Total chip usage among top 10000'), blank=True, size=6),
        ),
    ]
