# Generated by Django 3.1.4 on 2022-08-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0034_auto_20220807_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChipsAndUserInfo',
            new_name='PremierLeagueChipsAndUserInfo',
        ),
    ]
