# Generated by Django 3.1.4 on 2022-08-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0035_auto_20220807_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalOwnershipStats100',
            new_name='PremierLeagueGlobalOwnershipStats100',
        ),
        migrations.RenameModel(
            old_name='GlobalOwnershipStats1000',
            new_name='PremierLeagueGlobalOwnershipStats1000',
        ),
        migrations.RenameModel(
            old_name='GlobalOwnershipStats10000',
            new_name='PremierLeagueGlobalOwnershipStats10000',
        ),
        migrations.RenameModel(
            old_name='GwsChecked',
            new_name='PremierLeagueGwsChecked',
        ),
        migrations.RenameModel(
            old_name='NationalityStatistics',
            new_name='PremierLeagueNationalityStatistics',
        ),
    ]
