# Generated by Django 3.1.4 on 2022-08-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0036_auto_20220807_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfoStatistics',
            new_name='EliteserienUserInfoStatistics',
        ),
        migrations.RenameModel(
            old_name='FPLPlayersModel',
            new_name='PremierLeaguePlayers',
        ),
    ]
