# Generated by Django 3.1.4 on 2022-08-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0037_auto_20220807_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premierleaguechipsanduserinfo',
            old_name='total_chip_usage_5000',
            new_name='total_chip_usage_10000',
        ),
    ]
