# Generated by Django 4.1.7 on 2023-04-20 17:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0044_eliteserienplayerstatistic_fixture_id_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premierleagueplayers',
            name='fixture_id_list',
            field=django_mysql.models.ListTextField(models.IntegerField(blank=True, help_text='Fixture id (9)', null=True), default='', size=39),
            preserve_default=False,
        ),
    ]
