# Generated by Django 4.1.7 on 2023-06-03 13:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0048_eliteserienplayerstatistic_player_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='creativity_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of creativity (10.2)', max_length=6), size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='expected_assists_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_assists (0.06)', max_length=6), blank=True, null=True, size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='expected_goal_involvements_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goal_involvements (0.20)', max_length=6), blank=True, null=True, size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='expected_goals_conceded_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goals_conceded (1.6)', max_length=6), blank=True, null=True, size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='expected_goals_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of expected_goals (0.36)', max_length=6), blank=True, null=True, size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='ict_index_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of ict_index (3.6)', max_length=6), size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='influence_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter number of influence (10.6)', max_length=6), size=39),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='threat_list',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter threat value (10.0)', max_length=6), size=39),
        ),
    ]
