# Generated by Django 3.1.4 on 2024-08-08 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0051_auto_20240716_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremierLeagueSeasonMetadata',
            fields=[
                ('season_name', models.CharField(default='2023-2024', help_text='Season name: ', max_length=20, primary_key=True, serialize=False)),
                ('date_modified', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'PL - Season metadata',
                'verbose_name_plural': 'PL - Season metadata',
                'ordering': ['season_name'],
            },
        ),
        migrations.AlterField(
            model_name='eliteserienplayerstatistic',
            name='player_created_date',
            field=models.DateField(default=datetime.date(2024, 8, 8), help_text='Date entered into database'),
        ),
        migrations.AlterField(
            model_name='premierleagueplayers',
            name='player_created_date',
            field=models.DateField(default=datetime.date(2024, 8, 8), help_text='Date entered into database'),
        ),
    ]
