# Generated by Django 3.1.4 on 2024-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_statistics', '0052_auto_20240808_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteserienSeasonMetadata',
            fields=[
                ('season_name', models.CharField(default='2024', help_text='Season name: ', max_length=20, primary_key=True, serialize=False)),
                ('date_modified', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'ESF - Season metadata',
                'verbose_name_plural': 'ESF - Season metadata',
                'ordering': ['season_name'],
            },
        ),
    ]
